--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BeeAZZ/SeasonShop
build-by-default: true
branches:
- master
projects:
  SeasonShopUI:
    path: ""
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^2.0.0
...
