name: SeasonShop
version: 0.0.1
api: 5.0.0
main: BeeAZZ\SeasonShop\SeasonShop
author: BeeAZZ
description: Shop Season For Pocketmine-MP
softdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
 sshop:
  description: Season Shop
  aliases: ["ss"]
  permission: seasonshop.command
permissions:
 seasonshop.command:
  default: true
